// LSAT Compass — Group G: lr-resolve-paradox
// IDs lr-g-201 .. lr-g-220. All content original (sourceType: 'original').
//
// trapTypes lists the trap tags instantiated by the distractors (one per
// distractor, in choice order skipping the correct choice); each tag is drawn
// from the exact §6 taxonomy and is referenced in the corresponding
// choiceExplanation. In resolve-paradox items the correct choice reconciles
// BOTH surprising facts; distractors explain only one side, deepen the
// mystery, or are irrelevant.

import type { Question } from '../index';



export const QUESTIONS_LR_G: Question[] = [
  {
    id: 'lr-g-201',
    version: 1,
    sectionType: 'LR',
    questionType: 'lr-resolve-paradox',
    secondarySkills: ['f-structure', 'f-numbers'],
    editorialDifficulty: 2,
    difficultyProfile: { structuralComplexity: 2, inferentialDistance: 2, distractorProximity: 2 },
    itemPurpose: 'independent-blocked',
    validationStatus: 'validated',
    reviewHistory: [
      { date: '2026-09-11', reviewer: 'full-lr-classification-2026-09-11', verdict: 'validate',
        notes: 'Full-LR classification: KEEP. Denominator-shift resolution (more riders, lower per-rider rate); no second defensible answer; d2 honest.' },
    ],
    stimulus:
'After the city painted dedicated bike lanes on its downtown avenues, the number of reported cycling accidents rose by 30 percent. The lanes were built to make cycling safer, and they meet every national safety standard.',
    stem: 'Which one of the following, if true, most helps to explain the apparent discrepancy described above?',
    choices: [
      { text: 'The bike lanes were painted bright red to increase their visibility to drivers.' },
      { text: 'The new lanes drew first-time cyclists, and the accident rate fell.' },
      { text: 'Cycling accidents also rose in neighboring cities that built no bike lanes.' },
      { text: 'Most of the reported accidents involved experienced cyclists commuting to work.' },
      { text: 'Bicycle sales in the city were flat in the year the lanes were painted.' },
    ],
    correctIndex: 1,
    explanationQuick:
'More total accidents alongside safer lanes is reconciled by a surge in new, inexperienced riders: the absolute count rose because far more people were cycling, while each cyclist\'s risk fell. Choice (B) explains both facts — why accidents rose and why the lanes still improved safety. The distractors are irrelevant, explain only one side, or deepen the mystery.',
    explanationWalkthrough:
'Pin down the two surprising facts: (1) accidents rose 30% after the lanes were painted; (2) the lanes meet safety standards and were meant to reduce accidents. A resolution must make both true at once — it must explain the rise without denying the lanes\' safety. Choice (B) does this with a denominator shift: the lanes drew many first-time cyclists, so total accidents rose even as the per-cyclist rate fell. Both facts coexist: more riders overall, less risk per rider. Choice (A) is the irrelevant-true trap: lane color explains nothing about the accident count. Choice (C) is the half-right trap: it suggests a regional trend, but it does not explain why this city\'s lanes coincided with a rise — and a general trend would deepen, not resolve, the puzzle of safer lanes plus more accidents. Choice (D) deepens the mystery: if experienced cyclists — the least likely to crash — accounted for most accidents, the rise is even stranger. Choice (E) is the irrelevant-true trap: flat sales figures explain nothing about why accidents rose 30%.',
    choiceExplanations: [
'Lane color is irrelevant to the accident count — it explains neither the rise nor the lanes\' safety. An unrelated true-sounding detail is the irrelevant-true trap.',
'Correct. A surge of inexperienced new cyclists raises the absolute accident count while the per-cyclist rate falls — reconciling more total accidents with genuinely safer lanes.',
'A regional trend does not explain why safer lanes coincided with more accidents here; if anything, accidents rising everywhere makes the local safety improvement more puzzling. This is the half-right trap.',
'If experienced commuters — the safest riders — suffered most accidents, the rise becomes harder, not easier, to explain. A choice that deepens the mystery is the opposite trap.',
'Flat bicycle sales cannot explain a 30% rise in reported accidents — with no new bikes entering the picture, the sales figures are simply irrelevant. This is the irrelevant-true trap.',
    ],
    generalLesson:
'When totals and rates seem to conflict, look for a denominator shift: a growing population can raise absolute counts even as individual risk falls.',
    misconceptionTags: ['rate-vs-count', 'denominator-shift'],
    trapTypes: ['irrelevant-true', 'half-right', 'opposite', 'irrelevant-true'],
    prerequisites: ['lr-resolve-paradox', 'f-structure', 'f-numbers'],
    estimatedSeconds: 70,
    sourceType: 'original',
    hints: [
'Two facts must both stay true: accidents rose, and the lanes are safe. What could raise total accidents without making the lanes dangerous?',
'Think about who started cycling after the lanes appeared — and the difference between total accidents and accidents per cyclist.',
'The correct choice brings in new, inexperienced riders: more crashes overall, less risk per rider.',
    ],
    labels: { topic: 'bike lane accidents' },
  },
  {
    id: 'lr-g-202',
    version: 1,
    sectionType: 'LR',
    questionType: 'lr-resolve-paradox',
    secondarySkills: ['f-structure'],
    editorialDifficulty: 3,
    difficultyProfile: { structuralComplexity: 3, inferentialDistance: 3, distractorProximity: 3 },
    itemPurpose: 'independent-blocked',
    validationStatus: 'validated',
    reviewHistory: [
      { date: '2026-09-11', reviewer: 'full-lr-classification-2026-09-11', verdict: 'validate',
        notes: 'Full-LR classification: KEEP. Two-move resolution (use-shift + uncounted e-books); (E) is a proper half-right subset of (C); d3 honest.' },
    ],
    stimulus:
'Last year the public library extended its hours, opening evenings and Sundays for the first time. Yet the number of books checked out fell by 18 percent, even though foot traffic through the library increased.',
    stem: 'Which one of the following, if true, most helps to explain the apparent discrepancy described above?',
    choices: [
      { text: 'The library hired additional evening staff to cover the extended hours, which substantially raised operating costs.' },
      { text: 'A national bookstore chain announced it will open a branch near the library sometime next year.' },
      { text: 'New-hours visitors used computers and study rooms, as e-book lending — uncounted in checkouts — rose' },
      { text: 'The library reduced its budget for purchasing new physical books last year.' },
      { text: 'Checkout figures count only physical books borrowed in person, not digital loans.' },
    ],
    correctIndex: 2,
    explanationQuick:
'More visitors but fewer checkouts is reconciled when the new visitors use the library differently: evenings and Sundays drew computer users and studiers, while borrowing shifted to e-books that the checkout statistic does not count. Choice (C) explains both the foot-traffic rise and the checkout drop. The distractors are irrelevant, deepen the mystery, or explain only one side.',
    explanationWalkthrough:
'The surprise has two halves: foot traffic rose (more people, more hours) but physical checkouts fell 18%. A resolution must account for both — why more visitors borrowed fewer books. Choice (C) does it in two moves: the new hours attracted a different kind of use (computers, study space — no borrowing involved), and borrowing itself migrated to e-books, which the reported figures exclude. So the library is busier and lending is healthy; only the measured number fell. Choice (A) is the irrelevant-true trap: staffing explains how the hours were covered, not the checkout decline. Choice (B) is the irrelevant-true trap: a bookstore opening next year explains nothing about last year\'s figures — neither the checkout drop nor the traffic rise. Choice (D) also deepens the puzzle: fewer new books plus more visitors should not produce an 18% checkout collapse on its own, and it says nothing about the traffic increase. Choice (E) is the half-right trap: it notes the figures exclude e-books, which hints at a measurement gap, but without the facts that e-book lending actually rose and new visitors came for other purposes, it does not explain the divergence.',
    choiceExplanations: [
'Extra evening staff explains how the library stayed open, not why borrowing fell while visits rose. An unrelated operational detail is the irrelevant-true trap. Its truth is beside the point, since nothing in it connects to the inference being tested.',
'A bookstore opening next year cannot explain last year\'s checkout drop or the traffic increase — a future event explains neither surprising fact. This is the irrelevant-true trap. Its truth is beside the point, since nothing in it connects to the inference being tested.',
'Correct. New-hour visitors came for computers and study space rather than borrowing, and lending shifted to uncounted e-books — so visits rose while measured checkouts fell, with no real decline in use.',
'A smaller acquisitions budget might trim checkouts, but it leaves the foot-traffic increase unexplained and makes the divergence stranger. This deepens the mystery: the opposite trap.',
'That the figures exclude e-books hints at a gap, but without evidence that e-book lending rose and new visitors used the library differently, it does not explain the divergence. A partial explanation is the half-right trap.',
    ],
    generalLesson:
'When a metric falls while activity rises, check what the metric actually measures — and whether behavior shifted to something the metric cannot see.',
    misconceptionTags: ['metric-definition', 'behavior-shift'],
    trapTypes: ['irrelevant-true', 'irrelevant-true', 'opposite', 'half-right'],
    prerequisites: ['lr-resolve-paradox', 'f-structure'],
    estimatedSeconds: 85,
    sourceType: 'original',
    hints: [
'Foot traffic rose but checkouts fell. Could the new visitors be doing something other than borrowing books?',
'What does the checkout figure actually count — and what might it be missing?',
'The correct choice changes both what visitors do and what gets counted.',
    ],
    labels: { topic: 'library hours paradox' },
  },
  {
    id: 'lr-g-203',
    version: 1,
    sectionType: 'LR',
    questionType: 'lr-resolve-paradox',
    secondarySkills: ['f-structure'],
    editorialDifficulty: 1,
    difficultyProfile: { structuralComplexity: 1, inferentialDistance: 1, linguisticComplexity: 2 },
    itemPurpose: 'skill-acquisition',
    validationStatus: 'validated',
    reviewHistory: [
      { date: '2026-09-11', reviewer: 'full-lr-classification-2026-09-11', verdict: 'validate',
        notes: 'Full-LR classification: KEEP. Clean d1 skill-acquisition item; competitor-closure resolution; distractors appropriately simple.' },
    ],
    stimulus:
      "Marta's Diner raised its prices by 15 percent last month. Since then, the lunch line at the diner has grown noticeably longer.",
    stem: 'Which one of the following, if true, most helps to explain the apparent discrepancy described above?',
    choices: [
      { text: "The diner across the street, Marta's only competitor, closed" },
      { text: "Marta's Diner now uses more expensive organic ingredients." },
      { text: 'The diner kept its number of tables unchanged.' },
      { text: 'Customers have complained about the higher prices on social media.' },
      { text: 'The diner extended its lunch hours by thirty minutes each day.' },
    ],
    correctIndex: 0,
    explanationQuick:
'Higher prices should shrink demand, yet lines grew. Choice (A) resolves it: the only nearby competitor closed, so its customers had nowhere else to go — demand was pushed to Marta\'s regardless of price. The other choices explain the price rise, deepen the mystery, or address only one side.',
    explanationWalkthrough:
'The two facts: prices rose 15%, and the lunch line got longer. Normally higher prices mean fewer customers, so something must have shifted demand independently of price. Choice (A) supplies it: the sole nearby competitor closed, funneling its former customers to Marta\'s. Lines grow not because the price rise attracted anyone, but because the alternative disappeared. Choice (B) is the answers-different-question trap: expensive ingredients might justify the price increase, but they explain the price, not the longer lines. Choice (C) is the irrelevant-true trap: an unchanged table count explains nothing about the longer lines. Choice (D) also deepens it: complaints suggest customers are unhappy, making longer lines stranger. Choice (E) is the half-right trap: longer hours might spread the same crowd thinner, not concentrate it into longer lines; it touches operations without explaining the demand shift.',
    choiceExplanations: [
'Correct. With the only nearby competitor gone, its customers had to eat somewhere — demand shifted to Marta\'s despite higher prices, reconciling the price rise with the longer lines.',
'Costlier ingredients may explain why prices rose, but they do nothing to explain why more people are lining up. Explaining the price instead of the paradox is the answers-different-question trap.',
'An unchanged table count explains nothing about why the lunch line grew after a 15% price increase — a static background fact cannot resolve the paradox. This is the irrelevant-true trap.',
'Complaints about prices suggest customers dislike the increase, which makes their willingness to wait in longer lines stranger. This deepens the mystery: the opposite trap.',
'Longer hours spread diners over more time rather than concentrating them into longer lines. This operational detail does not explain the demand shift: the half-right trap.',
    ],
    generalLesson:
'When price and demand move the "wrong" way together, look for an external demand shift — like a competitor\'s exit — that overwhelms the price effect.',
    misconceptionTags: ['demand-shift', 'price-effect'],
    trapTypes: ['answers-different-question', 'irrelevant-true', 'opposite', 'half-right'],
    prerequisites: ['lr-resolve-paradox', 'f-structure'],
    estimatedSeconds: 55,
    sourceType: 'original',
    hints: [
'Higher prices usually mean fewer customers. What outside change could send more customers to the diner anyway?',
'Which choice changes the competitive landscape rather than the diner\'s costs or hours?',
'The correct choice removes the diner\'s only alternative — its customers have nowhere else to go.',
    ],
    labels: { topic: 'diner price paradox' },
  },
  {
    id: 'lr-g-204',
    version: 1,
    sectionType: 'LR',
    questionType: 'lr-resolve-paradox',
    secondarySkills: ['f-structure', 'f-causation'],
    editorialDifficulty: 3,
    difficultyProfile: { structuralComplexity: 2, inferentialDistance: 3, causalComplexity: 3 },
    itemPurpose: 'independent-blocked',
    validationStatus: 'validated',
    reviewHistory: [
      { date: '2026-09-11', reviewer: 'full-lr-classification-2026-09-11', verdict: 'validate',
        notes: 'Full-LR classification: KEEP. Strength-becomes-weakness (drought vs flood tolerance) mechanism; d3 honest.' },
    ],
    stimulus:
'Farmers in the valley planted a new drought-resistant seed variety this spring. Despite receiving normal rainfall, their yields per acre fell below those of the previous five years.',
    stem: 'Which one of the following, if true, most helps to explain the apparent discrepancy described above?',
    choices: [
      { text: 'The drought-resistant seeds cost considerably more than the traditional variety.' },
      { text: 'Spring floods hurt the new variety, which tolerates standing water poorly' },
      { text: 'Neighboring valleys that planted the traditional variety had normal yields.' },
      { text: 'The new seed variety was developed over twelve years of field trials.' },
      { text: 'Some farmers in the valley chose not to plant the new variety.' },
    ],
    correctIndex: 1,
    explanationQuick:
'Drought-resistant seeds plus normal rain should not cut yields — unless the seeds\' strength is also their weakness. Choice (B) resolves it: the spring brought record flooding, which this variety handles poorly. The other choices address cost, deepen the mystery, or leave the mechanism unexplained.',
    explanationWalkthrough:
'The surprise: a seed bred to protect yields coincided with the worst yields in five years, even though rainfall was normal — so drought cannot be the culprit. The resolution must supply a different threat that this variety is specifically vulnerable to. Choice (B) does: record flooding struck, and drought resistance came at the cost of flood tolerance. Both facts now fit — the seeds performed exactly as bred (against drought), but the actual enemy was water excess. Choice (A) is the irrelevant-true trap: higher seed cost affects profits, not yields per acre. Choice (C) deepens the mystery — if neighbors with traditional seeds did fine, the new variety looks even worse, with no mechanism offered. Choice (D) is irrelevant background about development time. Choice (E) is the half-right trap: some farmers opting out does not explain why those who planted the new seeds got poor yields.',
    choiceExplanations: [
'Seed cost affects the farmers\' expenses, not the bushels harvested per acre. An irrelevant financial detail is the irrelevant-true trap. Its truth is beside the point, since nothing in it connects to the inference being tested.',
'Correct. The variety resists drought but not flooding; a record-flood spring hit its specific weakness, so yields fell despite normal rainfall totals — both facts reconciled.',
'That neighbors did fine with traditional seeds confirms the new variety underperformed but offers no mechanism — making the failure more puzzling, not less. This is the opposite trap.',
'Twelve years of field trials is background trivia that explains nothing about this spring\'s yields. This is the irrelevant-true trap. Its truth is beside the point, since nothing in it connects to the inference being tested.',
'Some farmers opting out does not explain why the farmers who did plant the new variety harvested less. This addresses the wrong group: the half-right trap.',
    ],
    generalLesson:
'A trait bred for one threat can create vulnerability to another. When a safeguard coincides with failure, ask what different threat the safeguard left exposed.',
    misconceptionTags: ['tradeoff', 'threat-mismatch'],
    trapTypes: ['irrelevant-true', 'opposite', 'irrelevant-true', 'half-right'],
    prerequisites: ['lr-resolve-paradox', 'f-structure', 'f-causation'],
    estimatedSeconds: 80,
    sourceType: 'original',
    hints: [
'Rainfall was normal, so drought is not the story. What other weather threat could strike — and how might drought resistance relate to it?',
'Which choice gives the new variety a specific weakness that this spring actually exploited?',
'The correct choice pairs record flooding with the variety\'s poor tolerance for standing water.',
    ],
    labels: { topic: 'drought-resistant seeds' },
  },
  {
    id: 'lr-g-205',
    version: 1,
    sectionType: 'LR',
    questionType: 'lr-resolve-paradox',
    secondarySkills: ['f-structure'],
    editorialDifficulty: 2,
    difficultyProfile: { structuralComplexity: 2, inferentialDistance: 3, distractorProximity: 3, linguisticComplexity: 1 },
    itemPurpose: 'independent-blocked',
    validationStatus: 'validated',
    stimulus:
'A software company switched its engineers to a four-day workweek with no pay cut. In the six months that followed, the total number of features shipped per month increased.',
    stem: 'Which one of the following, if true, most helps to explain the apparent discrepancy described above?',
    choices: [
      { text: 'Engineers reported feeling happier and less burned out with the four-day schedule.' },
      { text: 'The company\'s headcount remained exactly flat during the same six-month period.' },
      { text: 'Fridays were status meetings; cutting them freed four days for coding.' },
      { text: 'The company\'s competitors also reduced their workweeks at some point last year.' },
      { text: 'Feature quality is not measured anywhere in the company\'s shipping statistics.' },
    ],
    correctIndex: 2,
    explanationQuick:
'Fewer hours should mean less output, yet output rose. Choice (C) resolves it: the eliminated day was mostly low-value meetings, so the remaining hours became far more productive — total productive time effectively grew. The distractors cite morale, flat headcount, competitors, or measurement gaps — none supplying the productivity mechanism.',
    explanationWalkthrough:
'The two facts: hours fell 20%, but shipped features per month rose. For both to hold, productivity per hour must have jumped enough to outweigh the lost day. Choice (C) supplies the mechanism: Fridays were largely status meetings — low-output time — and their elimination converted the other four days into deep, uninterrupted coding. The lost hours were the least productive ones, so effective coding time actually increased. Choice (A) is the half-right trap: happiness might correlate with productivity, but it does not explain how fewer hours produced more output — the mechanism is missing. Choice (B) is the irrelevant-true trap: flat headcount rules out the more-hands explanation, but it does nothing to resolve how fewer hours yielded more output. Choice (D) is the irrelevant-true trap: competitors\' schedules explain nothing about this company\'s output. Choice (E) deepens the mystery: if quality is unmeasured, the shipping count could mask shoddier work — making the "increase" suspect rather than explained.',
    choiceExplanations: [
'Happier engineers might work better, but morale alone does not explain how 20% fewer hours yielded more shipped features — the productivity mechanism is missing. This is the half-right trap.',
'With headcount flat, the output gain cannot be credited to more hands — this fact rules out one alternative without explaining how fewer hours yielded more features. A non-explanatory true fact is the irrelevant-true trap.',
'Correct. The cut day was mostly meetings; eliminating them turned four days into deep coding time, so productive hours effectively rose — reconciling fewer total hours with more shipped features.',
'What competitors did has no bearing on this company\'s output numbers, and it offers no mechanism for how fewer hours produced more features. An unrelated industry fact is the irrelevant-true trap.',
'If quality is unmeasured, the higher shipping count might reflect rushed, shoddy work — which makes the apparent gain more suspicious, not explained. This is the opposite trap.',
    ],
    generalLesson:
'Not all hours are equal: when less time yields more output, look for the eliminated hours having been the least productive ones.',
    misconceptionTags: ['hours-vs-output', 'productivity-composition'],
    trapTypes: ['half-right', 'irrelevant-true', 'irrelevant-true', 'opposite'],
    prerequisites: ['lr-resolve-paradox', 'f-structure'],
    estimatedSeconds: 70,
    sourceType: 'original',
    hints: [
'Fewer hours but more output means each remaining hour did more. What could make the remaining hours so much more productive?',
'Which choice says something specific about how the eliminated day had been spent?',
'The correct choice reveals the cut day was mostly meetings — the least productive hours.',
    ],
    labels: { topic: 'four-day workweek' },
    reviewHistory: [
      { date: '2026-09-11', reviewer: 'hostile-sample-2026-09-11', verdict: 'validate',
        notes: 'Independent 40-item hostile audit: KEEP; 0 two-defensible findings; leakage pass 2 applied.' },
    ],
  },  {
    id: 'lr-g-206',
    version: 1,
    sectionType: 'LR',
    questionType: 'lr-resolve-paradox',
    secondarySkills: ['f-structure', 'f-causation'],
    editorialDifficulty: 4,
    difficultyProfile: { structuralComplexity: 3, inferentialDistance: 4, distractorProximity: 3, causalComplexity: 3, linguisticComplexity: 2 },
    itemPurpose: 'mixed-discrimination',
    validationStatus: 'validated',
    stimulus:
'Two years after the town banned single-use plastic bags, the amount of plastic litter collected in parks and waterways has increased. The ban was intended to reduce plastic pollution, and compliance among retailers has been nearly total.',
    stem: 'Which one of the following, if true, most helps to explain the apparent discrepancy described above?',
    choices: [
      { text: 'Thick reusable bags, quickly discarded, put more plastic per bag into waste than the banned bags did.' },
      { text: 'The town also banned plastic straws in the same ordinance.' },
      { text: 'Shoppers switched to paper bags, which tear easily and scatter in the wind, increasing visible litter even though paper is not plastic.' },
      { text: 'Plastic litter has also increased in neighboring towns without bag bans.' },
      { text: 'Retailers complied with the ban by switching to bags made of recycled plastic.' },
    ],
    correctIndex: 0,
    explanationQuick:
'A fully obeyed ban on thin plastic bags coinciding with more plastic litter is reconciled by substitution with a worse offender: choice (A) — shoppers replaced the thin banned bags with thick reusable plastic bags that they discard after only a few uses, each putting more plastic into the waste stream than a banned bag did. Full compliance plus more plastic per bag yields more plastic litter. The distractors cite unrelated items, non-plastic substitutes, regional trends, or imply the ban changed nothing.',
    explanationWalkthrough:
      'The tension: retailers nearly totally complied with the thin-bag ban, yet collected plastic litter rose. For both to hold, the plastic in the litter must come from a source the ban did not remove — or from a replacement worse than the original. Choice (A) supplies exactly that: shoppers switched to thick reusable plastic bags but discard them after only a few uses, and each such bag contains more plastic than a thin banned bag did. Full compliance is preserved (no thin bags sold), while total plastic entering the waste stream increases — so collected plastic litter rises, and both facts hold with no contradiction. Choice (B) is the irrelevant-true trap: straws are a different item and explain nothing about bag litter. Choice (C) is the opposite trap: paper bags are not plastic, so switching to paper cannot explain more plastic litter — it should reduce it. Choice (D) is the half-right trap: a regional trend widens the puzzle without explaining this town\'s ban-versus-litter divergence. Choice (E) is the opposite trap: recycled-plastic bags are still plastic bags, implying the ban changed nothing and contradicting near-total compliance.',
    choiceExplanations: [
'Correct. The ban eliminated thin single-use bags, but shoppers replaced them with thick reusable plastic bags discarded after only a few uses — each containing more plastic than the banned bags. Total plastic entering the waste stream therefore rose even with full compliance, directly explaining why collected plastic litter increased.',
'A straw ban is a separate provision about a separate item; it explains nothing about why plastic-bag litter rose. An unrelated fact from the same ordinance is the irrelevant-true trap.',
'Paper bags are not plastic, so a switch to paper cannot explain an increase in plastic litter — if anything it should reduce it. This choice deepens the mystery rather than resolving it: the opposite trap.',
'That litter also rose elsewhere does not explain why this town\'s fully obeyed ban coincided with more plastic litter; it merely widens the puzzle. A regional trend without a mechanism is the half-right trap.',
'Recycled-plastic bags are still plastic bags, so this would mean the ban changed nothing — contradicting the premise of near-total compliance with a meaningful ban. This is the opposite trap.',
    ],    generalLesson:
'Bans target one product, but behavior substitutes another: when a prohibition coincides with a worsening metric, trace what replaced the banned item.',
    misconceptionTags: ['substitution-effect', 'metric-scope'],
    trapTypes: ['irrelevant-true', 'opposite', 'half-right', 'opposite'],
    prerequisites: ['lr-resolve-paradox', 'f-structure', 'f-causation'],
    estimatedSeconds: 95,
    sourceType: 'original',
    hints: [
'The ban removed thin bags — but what did shoppers carry their groceries in instead?',
'Which choice describes a replacement that puts MORE plastic into the waste stream per bag?',
'The correct choice: thick reusable bags discarded after a few uses, each containing more plastic than the banned bags.',
    ],    labels: { topic: 'plastic bag ban' },
    reviewHistory: [
      { date: '2026-09-11', reviewer: 'hostile-sample-2026-09-11', verdict: 'validate',
        notes: 'Independent 40-item hostile audit: KEEP; 0 two-defensible findings; leakage pass 2 applied.' },
    ],
  },
  {
    id: 'lr-g-207',
    version: 1,
    sectionType: 'LR',
    questionType: 'lr-resolve-paradox',
    secondarySkills: ['f-structure'],
    editorialDifficulty: 2,
    difficultyProfile: { structuralComplexity: 2, inferentialDistance: 2, distractorProximity: 2 },
    itemPurpose: 'independent-blocked',
    validationStatus: 'validated',
    reviewHistory: [
      { date: '2026-09-11', reviewer: 'full-lr-classification-2026-09-11', verdict: 'validate',
        notes: 'Full-LR classification: KEEP. Local-compliance mechanism (brake-then-speed); (B) genuine half-right; d2 honest.' },
    ],
    stimulus:
'After speed cameras were installed along the highway, the number of speeding tickets issued fell by half. Yet the highway accident rate remained exactly the same.',
    stem: 'Which one of the following, if true, most helps to explain the apparent discrepancy described above?',
    choices: [
      { text: 'Drivers brake for cameras then speed up, so speeds and crash risk stay unchanged' },
      { text: 'The cameras are clearly marked with warning signs a mile in advance.' },
      { text: 'Speeding tickets had been rising steadily for five years before the cameras were installed.' },
      { text: 'The accident rate on nearby highways without cameras also stayed the same.' },
      { text: 'Camera fines are significantly higher than the fines officers used to issue.' },
    ],
    correctIndex: 0,
    explanationQuick:
'Fewer tickets but unchanged accidents is reconciled when driver behavior changed only at the cameras: drivers slow for the lens, then speed again — tickets fall, real risk does not. Choice (A) explains both facts. The distractors are irrelevant details, background trends, or deepen the mystery.',
    explanationWalkthrough:
'Two facts: tickets halved, accidents unchanged. Tickets measure caught speeding at camera points; accidents measure actual road risk. For both to hold, the cameras must have changed ticketed behavior without changing real driving risk. Choice (A) supplies the mechanism: drivers brake for the cameras and re-accelerate after — compliance is local and theatrical, so tickets drop while average speeds and crash risk stay flat. Choice (B) is the half-right trap: warning signs might explain fewer tickets (drivers slow in time), but not why accidents stayed the same. Choice (C) is background trivia about pre-camera trends — the irrelevant-true trap. Choice (D) is also half-right: unchanged rates elsewhere do not explain this highway\'s ticket-accident divergence. Choice (E) deepens the mystery: higher fines should deter speeding more, making unchanged accidents stranger — the opposite trap.',
    choiceExplanations: [
'Correct. Localized braking cuts tickets at camera points while post-camera speeding keeps average speeds and crash risk unchanged — reconciling fewer tickets with flat accident rates.',
'Warning signs might explain why tickets fell (drivers brake in time), but they do not explain why accidents stayed flat. Explaining only one side is the half-right trap.',
'The pre-camera trend in tickets is background that touches neither the ticket drop nor the flat accident rate. This is the irrelevant-true trap. Its truth is beside the point, since nothing in it connects to the inference being tested.',
'Unchanged rates on other highways do not explain this highway\'s divergence between tickets and accidents. This is the half-right trap. It captures part of the structure while missing the load-bearing element, which is exactly why it fails.',
'Higher fines should deter speeding more strongly, which makes unchanged accident rates more puzzling, not less. This deepens the mystery: the opposite trap. Since it points in the opposite direction from the argument\'s conclusion, it cannot supply what the stem asks for.',
    ],
    generalLesson:
'Enforcement metrics and outcome metrics can diverge when people comply only where they are watched. Ask whether the measured behavior changed everywhere or just at the sensor.',
    misconceptionTags: ['measurement-point', 'local-compliance'],
    trapTypes: ['half-right', 'irrelevant-true', 'half-right', 'opposite'],
    prerequisites: ['lr-resolve-paradox', 'f-structure'],
    estimatedSeconds: 65,
    sourceType: 'original',
    hints: [
'Tickets measure speeding at the cameras; accidents measure real risk. Could drivers behave differently at those two "locations"?',
'Which choice has drivers changing behavior only where the cameras watch?',
'The correct choice: brake for the lens, speed up after — tickets fall, risk does not.',
    ],
    labels: { topic: 'speed cameras' },
  },
  {
    id: 'lr-g-208',
    version: 1,
    sectionType: 'LR',
    questionType: 'lr-resolve-paradox',
    secondarySkills: ['f-structure', 'f-numbers'],
    editorialDifficulty: 3,
    difficultyProfile: { structuralComplexity: 2, inferentialDistance: 3, abstraction: 2 },
    itemPurpose: 'independent-blocked',
    validationStatus: 'validated',
    reviewHistory: [
      { date: '2026-09-11', reviewer: 'full-lr-classification-2026-09-11', verdict: 'validate',
        notes: 'Full-LR classification: KEEP. Self-selection composition effect on the reported average; d3 honest.' },
    ],
    stimulus:
'When Westfield College made standardized test scores optional for applicants, the average test score among enrolled students rose the following year.',
    stem: 'Which one of the following, if true, most helps to explain the apparent discrepancy described above?',
    choices: [
      { text: 'The college also increased its financial aid budget that year.' },
      { text: 'Applications to Westfield rose sharply after the policy change, though the college admitted the same percentage of applicants as before.' },
      { text: 'High school grade averages among enrolled students stayed the same.' },
      { text: 'After scores became optional, only applicants with strong scores chose to submit them.' },
      { text: 'Westfield\'s admissions office hired additional readers to review applications holistically.' },
    ],
    correctIndex: 3,
    explanationQuick:
'Optional scores plus a higher average is reconciled by self-selection: when only strong scorers submit, the reported average is computed over a stronger pool. Choice (D) explains it — the average rose because weak scores simply stopped being reported. The distractors cite aid, volume, or staffing, which do not touch the average\'s composition.',
    explanationWalkthrough:
'The surprise: making scores optional raised the average score. But "average test score among enrolled students" is computed only over students who submitted scores. If low scorers withhold their scores while high scorers submit, the average of the submitted scores rises mechanically — no student needs to have scored higher. Choice (D) states exactly this self-selection: only strong scorers submitted. Both facts hold: scores became optional, and the reported average rose, because the pool being averaged changed. Choice (A) is the irrelevant-true trap: financial aid does not change which scores get submitted. Choice (B) is the irrelevant-true trap: with the acceptance rate unchanged, more applications cannot explain the higher average. Choice (C) deepens the mystery: unchanged grades make the score jump stranger. Choice (E) is irrelevant: more readers do not alter the composition of submitted scores.',
    choiceExplanations: [
'Financial aid affects who can afford to attend, not which test scores get submitted. An unrelated policy change is the irrelevant-true trap. Its truth is beside the point, since nothing in it connects to the inference being tested.',
'With the acceptance rate unchanged, a larger applicant pool cannot explain a higher average among enrolled students — selectivity did not rise. This blocks the alternative story without resolving anything: the irrelevant-true trap.',
'If grades were flat while reported scores jumped, the divergence is even stranger. This deepens the mystery: the opposite trap. Since it points in the opposite direction from the argument\'s conclusion, it cannot supply what the stem asks for.',
'Correct. The average is computed over submitted scores only; when weak scorers withhold theirs, the reported average rises mechanically — reconciling optional scores with a higher average.',
'Additional readers change how applications are reviewed, not which scores applicants choose to submit. This is the irrelevant-true trap. Its truth is beside the point, since nothing in it connects to the inference being tested.',
    ],
    generalLesson:
'Averages follow the reporting pool, not just the underlying population: when reporting becomes voluntary, ask who opts out before concluding anything improved.',
    misconceptionTags: ['selection-bias', 'average-composition'],
    trapTypes: ['irrelevant-true', 'irrelevant-true', 'opposite', 'irrelevant-true'],
    prerequisites: ['lr-resolve-paradox', 'f-structure', 'f-numbers'],
    estimatedSeconds: 80,
    sourceType: 'original',
    hints: [
'The "average score" is averaged over whom — all students, or only those who submitted scores?',
'If weak scorers stopped submitting, what happens to the average of the scores that remain?',
'The correct choice: only strong scorers submitted, so the reported average rose by selection.',
    ],
    labels: { topic: 'test-optional admissions' },
  },
  {
    id: 'lr-g-209',
    version: 1,
    sectionType: 'LR',
    questionType: 'lr-resolve-paradox',
    secondarySkills: ['f-structure'],
    editorialDifficulty: 1,
    difficultyProfile: { structuralComplexity: 1, inferentialDistance: 2, linguisticComplexity: 1 },
    itemPurpose: 'skill-acquisition',
    validationStatus: 'validated',
    reviewHistory: [
      { date: '2026-09-11', reviewer: 'full-lr-classification-2026-09-11', verdict: 'validate',
        notes: 'Full-LR classification: KEEP. Clean d1 skill-acquisition item; product-degradation mechanism; (A) correctly half-right.' },
    ],
    stimulus:
'A downtown gym cut its monthly membership fee in half. In the three months that followed, average daily attendance fell by a third.',
    stem: 'Which one of the following, if true, most helps to explain the apparent discrepancy described above?',
    choices: [
      { text: 'Cheaper memberships attracted many new sign-ups who rarely work out.' },
      { text: 'To afford the fee cut, the gym cut classes and hours.' },
      { text: 'The gym advertised the lower fee heavily on social media.' },
      { text: 'Nearby gyms kept their fees unchanged during the same period.' },
      { text: 'The fee cut applied only to new members, not to existing ones.' },
    ],
    correctIndex: 1,
    explanationQuick:
'Cheaper memberships should raise attendance, yet attendance fell. Choice (B) resolves it: the fee cut was funded by canceling popular classes and cutting hours — the gym became less worth visiting, so regulars stopped coming. The other choices explain sign-ups, deepen the mystery, or miss the mechanism.',
    explanationWalkthrough:
'Two facts: price halved, attendance fell by a third. Lower prices normally increase use, so something must have made the gym less attractive at the same time. Choice (B) supplies it: the fee cut was paid for by eliminating the most popular classes and shortening hours — the product got worse as the price fell, and worse product drove regulars away faster than the low price attracted anyone. Choice (A) is the half-right trap: new sign-ups who never come explain flat attendance, not a one-third drop — and it cannot explain why existing regulars vanished. Choice (C) deepens the mystery: heavy advertising should have raised attendance. Choice (D) is the irrelevant-true trap: competitors\' unchanged fees do not explain this gym\'s attendance drop. Choice (E) is also half-right: limiting the cut to new members might mute the price effect, but it does not explain an actual decline.',
    choiceExplanations: [
'New sign-ups who never work out add little to daily attendance, but they cannot explain why attendance fell by a third — existing regulars must have left. This explains only one side: the half-right trap.',
'Correct. Funding the fee cut by canceling popular classes and reducing hours made the gym less worth visiting, so regulars stopped coming — reconciling the lower price with lower attendance.',
'Heavy advertising should increase attendance, making the drop stranger. This deepens the mystery: the opposite trap. Since it points in the opposite direction from the argument\'s conclusion, it cannot supply what the stem asks for.',
'Competitors\' pricing does not explain why this gym\'s own attendance fell. An unrelated market fact is the irrelevant-true trap. Its truth is beside the point, since nothing in it connects to the inference being tested.',
'Restricting the cut to new members might weaken the price effect, but it cannot produce an actual attendance decline. This is the half-right trap. It captures part of the structure while missing the load-bearing element, which is exactly why it fails.',
    ],
    generalLesson:
'Price cuts funded by quality cuts can reduce demand: when price and quantity move the "wrong" way, check whether the product itself changed.',
    misconceptionTags: ['price-vs-quality', 'product-change'],
    trapTypes: ['half-right', 'opposite', 'irrelevant-true', 'half-right'],
    prerequisites: ['lr-resolve-paradox', 'f-structure'],
    estimatedSeconds: 55,
    sourceType: 'original',
    hints: [
'Lower prices should bring more people. What change could make the gym less appealing at the same time the price fell?',
'Which choice says the gym itself got worse — not just cheaper?',
'The correct choice funds the fee cut by cutting popular classes and hours.',
    ],
    labels: { topic: 'gym fee cut' },
  },
  {
    id: 'lr-g-210',
    version: 1,
    sectionType: 'LR',
    questionType: 'lr-resolve-paradox',
    secondarySkills: ['f-structure', 'f-numbers'],
    editorialDifficulty: 4,
    difficultyProfile: { structuralComplexity: 3, inferentialDistance: 4, distractorProximity: 3 },
    itemPurpose: 'mixed-discrimination',
    validationStatus: 'validated',
    reviewHistory: [
      { date: '2026-09-11', reviewer: 'full-lr-classification-2026-09-11', verdict: 'validate',
        notes: 'Full-LR classification: KEEP. Reported-vs-actual crime distinction with full mechanism; (C) regional trend is a designed near-miss that never engages the funding fact; d4 honest.' },
    ],
    stimulus:
'Last year the country doubled funding for its police forces. Over the same period, the number of reported crimes rose by 25 percent.',
    stem: 'Which one of the following, if true, most helps to explain the apparent discrepancy described above?',
    choices: [
      { text: 'The additional funding was spent mostly on community outreach programs rather than on patrols, which do not directly affect whether crimes get reported to the police.' },
      { text: 'The country\'s unemployment rate held steady during the same period, ruling out economic distress as a driver of the increase.' },
      { text: 'Neighboring countries that did not increase police funding also saw reported crime rise, suggesting a regional trend in reporting that has nothing to do with policing levels.' },
      { text: 'Most of the new funding went unspent due to bureaucratic delays, so few additional officers were actually hired.' },
      { text: 'New officers went to under-policed neighborhoods, where residents stopped reporting crimes, so reporting soared while actual victimization stayed flat.' },
    ],
    correctIndex: 4,
    explanationQuick:
'More police plus more reported crime is reconciled when "reported" is the operative word: new officers in long-unpoliced neighborhoods caused crimes to be reported that previously went unrecorded, while actual crime stayed flat. Choice (E) explains the rise in reports without any rise in crime. The distractors cite steady unemployment, regional trends, or unspent funds — none distinguishing reported crime from actual crime.',
    explanationWalkthrough:
'The key distinction is reported crime versus actual crime. More police funding should reduce actual crime, but the statistic measures reports — and police presence itself increases reporting. Choice (E) builds the full mechanism: officers went to neighborhoods with almost no prior presence, where residents had given up reporting; reports soared there while actual victimization stayed flat. Both facts hold: funding doubled, reported crime rose 25%, yet policing did not fail — it illuminated dark figures of crime. Choice (A) is the half-right trap: outreach spending might explain why crime did not fall, but not why reports rose. Choice (B) is the irrelevant-true trap: steady unemployment eliminates one alternative cause, but it does not explain the 25% rise in reports — the funding-versus-reports tension is untouched. Choice (C) is the half-right trap: a regional trend does not explain this country\'s specific funding-crime divergence. Choice (D) deepens the mystery differently: unspent funds would predict no change, not a 25% rise in reports.',
    choiceExplanations: [
'Outreach spending might explain flat crime, but it does not explain why reported crimes rose by a quarter. This addresses only one side: the half-right trap.',
'Steady unemployment rules out an economic cause, but it explains nothing about why reported crimes rose 25% while police funding doubled. A true but non-explanatory fact is the irrelevant-true trap.',
'A regional trend does not explain why this country\'s funding increase coincided with more reported crime. Widening the puzzle is the half-right trap. It captures part of the structure while missing the load-bearing element, which is exactly why it fails.',
'Unspent funds would predict little change, not a 25% jump in reports. This leaves the rise unexplained: the unsupported trap. With the key claim left unsupported by any evidence, it cannot do the work the correct choice does.',
'Correct. New officers in previously unpoliced neighborhoods caused long-unreported crimes to be reported; reports soared while actual victimization stayed flat — reconciling more funding with more reported crime.',
    ],
    generalLesson:
'Reported statistics measure reporting behavior as well as underlying reality: when enforcement rises alongside reports, ask whether the rise is in recording rather than in occurrence.',
    misconceptionTags: ['reported-vs-actual', 'measurement-effect'],
    trapTypes: ['half-right', 'irrelevant-true', 'half-right', 'unsupported'],
    prerequisites: ['lr-resolve-paradox', 'f-structure', 'f-numbers'],
    estimatedSeconds: 95,
    sourceType: 'original',
    hints: [
'The statistic is reported crime, not necessarily committed crime. How could more police increase reporting without increasing crime?',
'Which choice puts new officers where crimes previously went unreported?',
'The correct choice: new presence in unpoliced neighborhoods turned silent victimization into reported crime.',
    ],
    labels: { topic: 'police funding paradox' },
  },
  {
    id: 'lr-g-211',
    version: 1,
    sectionType: 'LR',
    questionType: 'lr-resolve-paradox',
    secondarySkills: ['f-structure'],
    editorialDifficulty: 3,
    difficultyProfile: { structuralComplexity: 2, inferentialDistance: 3, distractorProximity: 2 },
    itemPurpose: 'independent-blocked',
    validationStatus: 'validated',
    reviewHistory: [
      { date: '2026-09-11', reviewer: 'full-lr-classification-2026-09-11', verdict: 'validate',
        notes: 'Full-LR classification: KEEP. Revenue-loss-exceeds-savings mechanism; d3 honest.' },
    ],
    stimulus:
'A bakery switched to a cheaper flour to cut costs. In the quarter that followed, its profits fell instead of rising.',
    stem: 'Which one of the following, if true, most helps to explain the apparent discrepancy described above?',
    choices: [
      { text: "Cheaper flour hurt taste, and the bakery lost regular customers" },
      { text: 'The bakery kept the prices of its pastries unchanged during the same quarter.' },
      { text: 'Flour prices across the industry fell during the same quarter.' },
      { text: 'The bakery\'s ovens are more than twenty years old.' },
      { text: 'The cheaper flour required slightly longer baking times.' },
    ],
    correctIndex: 0,
    explanationQuick:
'Cheaper inputs should raise profits, yet profits fell. Choice (A) resolves it: the flour hurt the taste, regulars left, and the lost revenue outweighed the ingredient savings. The distractors deepen the mystery, cite industry trends, or offer trivial operational details.',
    explanationWalkthrough:
'Two facts: input costs fell, but profits fell too. For both to hold, revenue must have fallen by more than costs did — the savings were swamped by lost sales. Choice (A) supplies the mechanism: worse taste drove away regulars, so the revenue loss exceeded the flour savings. Choice (B) is the irrelevant-true trap: unchanged pastry prices explain nothing about the profit decline, leaving the core tension untouched. Choice (C) is the irrelevant-true trap: industry flour prices do not explain this bakery\'s profit drop. Choice (D) is irrelevant background about oven age. Choice (E) is the half-right trap: slightly longer baking times are a minor operational wrinkle that cannot plausibly explain a profit decline — it gestures at a cost without the revenue mechanism.',
    choiceExplanations: [
'Correct. The cheaper flour degraded the product, regulars left, and the resulting revenue loss exceeded the ingredient savings — reconciling lower costs with lower profits.',
'Unchanged pastry prices explain nothing about why profits fell after the flour switch — a static fact cannot account for the decline. This is the irrelevant-true trap.',
'Industry-wide flour prices do not explain why this bakery\'s profits fell after its own cost cut. An unrelated market fact is the irrelevant-true trap. Its truth is beside the point, since nothing in it connects to the inference being tested.',
'The age of the ovens is background trivia that changed nothing this quarter and explains neither the cost cut nor the profit drop. This is the irrelevant-true trap.',
'Slightly longer baking times are too trivial to explain a profit decline and say nothing about lost revenue. A minor detail without the revenue mechanism is the half-right trap.',
    ],
    generalLesson:
'Cost cuts that degrade the product can destroy more revenue than they save: when lower costs coincide with lower profits, look for the demand side.',
    misconceptionTags: ['cost-vs-revenue', 'quality-demand'],
    trapTypes: ['irrelevant-true', 'irrelevant-true', 'irrelevant-true', 'half-right'],
    prerequisites: ['lr-resolve-paradox', 'f-structure'],
    estimatedSeconds: 75,
    sourceType: 'original',
    hints: [
'Lower costs should raise profits. For profits to fall anyway, what must have happened to revenue?',
'Which choice connects the cheaper flour to lost sales?',
'The correct choice: worse taste drove regulars away, and lost revenue outweighed the savings.',
    ],
    labels: { topic: 'bakery flour switch' },
  },
  {
    id: 'lr-g-212',
    version: 1,
    sectionType: 'LR',
    questionType: 'lr-resolve-paradox',
    secondarySkills: ['f-structure', 'f-numbers'],
    editorialDifficulty: 2,
    difficultyProfile: { structuralComplexity: 2, inferentialDistance: 2, distractorProximity: 2 },
    itemPurpose: 'independent-blocked',
    validationStatus: 'validated',
    reviewHistory: [
      { date: '2026-09-11', reviewer: 'full-lr-classification-2026-09-11', verdict: 'validate',
        notes: 'Full-LR classification: KEEP. Per-visitor revenue arithmetic; d2 honest.' },
    ],
    stimulus:
      "An aquarium lowered its admission prices by 20 percent. Attendance rose sharply, yet total admission revenue for the season fell.",
    stem: 'Which one of the following, if true, most helps to explain the apparent discrepancy described above?',
    choices: [
      { text: 'The aquarium extended its opening hours during the same season, adding two extra hours each weekend.' },
      { text: 'Visitors spent less per person at the gift shop and café than in previous seasons, a decline unrelated to ticket pricing or attendance levels.' },
      { text: 'The price cut applied mainly to group tickets already discounted, so revenue per visitor fell more than attendance rose.' },
      { text: 'A nearby zoo raised its admission prices during the same season, prompting complaints from local families.' },
      { text: 'The aquarium\u2019s most popular exhibit was closed for renovation for part of the season, reopening before the holidays.' },
    ],
    correctIndex: 2,
    explanationQuick:
'Lower prices plus more visitors should raise revenue — unless revenue per visitor fell faster than attendance grew. Choice (C) resolves it: the discount concentrated on already-cheap group tickets, so the average take per visitor dropped more than headcount rose. The distractors address hours, non-admission spending, competitors, or exhibits without the per-visitor arithmetic.',
    explanationWalkthrough:
'Revenue equals attendance times revenue per visitor. Attendance rose, so for revenue to fall, revenue per visitor must have fallen proportionally more. Choice (C) gives the arithmetic: the 20% cut landed mostly on group tickets that were already deeply discounted, dragging average revenue per visitor down faster than the attendance gain. Both facts hold: more visitors, less total revenue. Choice (A) is the half-right trap: longer hours might explain higher attendance but not falling revenue. Choice (B) is the irrelevant-true trap: gift-shop and café spending is not admission revenue, so it cannot explain the admission-revenue arithmetic at all. Choice (D) is the irrelevant-true trap: the zoo\'s prices do not explain the aquarium\'s revenue arithmetic. Choice (E) deepens the mystery: a closed star exhibit should have reduced attendance, yet attendance rose.',
    choiceExplanations: [
'Longer hours might explain the attendance gain, but they do nothing to explain why revenue fell despite more visitors. Explaining only one side is the half-right trap.',
'Gift-shop and café spending is not admission revenue, so lower side spending cannot explain a fall in admission revenue at all. It answers about the wrong revenue stream: the irrelevant-true trap.',
'Correct. Because the discount concentrated on already-cheap group tickets, average revenue per visitor fell by a larger percentage than attendance rose — so total revenue fell despite the crowds.',
'The zoo\'s pricing does not change the aquarium\'s revenue arithmetic. An unrelated competitor fact is the irrelevant-true trap. Its truth is beside the point, since nothing in it connects to the inference being tested.',
'A closed star exhibit should have hurt attendance, yet attendance rose — making the facts stranger, not clearer. This is the opposite trap. Since it points in the opposite direction from the argument\'s conclusion, it cannot supply what the stem asks for.',
    ],
    generalLesson:
'Revenue is price times quantity: when a price cut plus higher volume yields less revenue, check whether the cut fell unevenly and dragged the average price down disproportionately.',
    misconceptionTags: ['price-volume', 'average-revenue'],
    trapTypes: ['half-right', 'irrelevant-true', 'irrelevant-true', 'opposite'],
    prerequisites: ['lr-resolve-paradox', 'f-structure', 'f-numbers'],
    estimatedSeconds: 70,
    sourceType: 'original',
    hints: [
'Revenue is attendance multiplied by revenue per visitor. If attendance rose but revenue fell, what must have happened to revenue per visitor?',
'Which choice explains a steep drop in the average take per visitor?',
'The correct choice: the discount hit already-cheap group tickets hardest, so average revenue per visitor plunged.',
    ],
    labels: { topic: 'aquarium pricing' },
  },
  {
    id: 'lr-g-213',
    version: 1,
    sectionType: 'LR',
    questionType: 'lr-resolve-paradox',
    secondarySkills: ['f-structure', 'f-causation'],
    editorialDifficulty: 3,
    difficultyProfile: { structuralComplexity: 2, inferentialDistance: 3, distractorProximity: 3 },
    itemPurpose: 'independent-blocked',
    validationStatus: 'validated',
    reviewHistory: [
      { date: '2026-09-11', reviewer: 'full-lr-classification-2026-09-11', verdict: 'validate',
        notes: 'Full-LR classification: KEEP. Net-shade-loss mechanism; (A) is a model half-right (explains no-fall, not rise); d3 honest.' },
    ],
    stimulus:
'The city planted 10,000 new trees last year as part of a cooling initiative. Yet average summer temperatures in the city rose slightly.',
    stem: 'Which one of the following, if true, most helps to explain the apparent discrepancy described above?',
    choices: [
      { text: 'The newly planted trees were saplings that will not provide meaningful shade for at least a decade.' },
      { text: 'The city also expanded its bus network during the same year.' },
      { text: 'Residents were encouraged to water the new trees during dry spells.' },
      { text: 'The planting cleared mature shade trees; saplings cannot match their cooling for years' },
      { text: 'Tree-planting initiatives are popular with voters in the region.' },
    ],
    correctIndex: 3,
    explanationQuick:
'More trees should cool the city, yet temperatures rose. Choice (D) resolves it: planting the saplings required clearing mature shade trees first, so the city lost immediate cooling — a net loss of shade in the short run. The distractors note the saplings\' immaturity without the clearing, or cite irrelevant facts.',
    explanationWalkthrough:
'Two facts: 10,000 trees planted, but summer temperatures rose. New plantings cool only when they add net shade; if planting destroyed existing shade, the short-term effect reverses. Choice (D) supplies both halves: mature shade trees were cleared to make room, and saplings cannot replace their cooling for years — net shade fell, so temperatures rose, fully consistent with the planting count. Choice (A) is the half-right trap: sapling immaturity explains why temperatures did not fall, but not why they rose — something must have actively removed cooling. Choice (B) is the irrelevant-true trap: bus expansion does not explain the temperature rise. Choice (C) is irrelevant: watering does not affect city temperatures. Choice (E) is the irrelevant-true trap: voter popularity explains nothing about thermometers.',
    choiceExplanations: [
'Sapling immaturity explains why temperatures did not fall, but not why they rose — an active loss of cooling is still missing. Explaining only one side is the half-right trap.',
'Bus network expansion has no bearing on summer temperatures. An unrelated civic fact is the irrelevant-true trap. Its truth is beside the point, since nothing in it connects to the inference being tested.',
'Watering new trees does not change citywide temperatures. This is the irrelevant-true trap. Its truth is beside the point, since nothing in it connects to the inference being tested.',
'Correct. Clearing mature shade trees to plant saplings produced a net loss of shade in the short run — so temperatures rose even as the tree count grew, reconciling both facts.',
'Voter popularity explains why the program exists, not why temperatures rose. This is the irrelevant-true trap. Its truth is beside the point, since nothing in it connects to the inference being tested.',
    ],
    generalLesson:
'Gross counts can mask net losses: when an addition coincides with a worsening outcome, ask what was removed to make room for it.',
    misconceptionTags: ['gross-vs-net', 'short-run-effect'],
    trapTypes: ['half-right', 'irrelevant-true', 'irrelevant-true', 'irrelevant-true'],
    prerequisites: ['lr-resolve-paradox', 'f-structure', 'f-causation'],
    estimatedSeconds: 80,
    sourceType: 'original',
    hints: [
'Planting 10,000 trees adds shade eventually — but what had to be removed to plant them?',
'Which choice describes an immediate loss of cooling, not just a delayed gain?',
'The correct choice: mature shade trees were cleared, and saplings cannot replace them for years.',
    ],
    labels: { topic: 'urban tree planting' },
  },
  {
    id: 'lr-g-214',
    version: 1,
    sectionType: 'LR',
    questionType: 'lr-resolve-paradox',
    secondarySkills: ['f-structure'],
    editorialDifficulty: 2,
    difficultyProfile: { structuralComplexity: 2, inferentialDistance: 2, distractorProximity: 2 },
    itemPurpose: 'independent-blocked',
    validationStatus: 'validated',
    reviewHistory: [
      { date: '2026-09-11', reviewer: 'full-lr-classification-2026-09-11', verdict: 'validate',
        notes: 'Full-LR classification: KEEP. Demand-outruns-capacity mechanism; (C) correctly deepens the mystery; d2 honest.' },
    ],
    stimulus:
'The regional hospital added 40 new beds last year. Yet average emergency-room wait times increased.',
    stem: 'Which one of the following, if true, most helps to explain the apparent discrepancy described above?',
    choices: [
      { text: 'The new beds are located in a newly built wing with modern equipment that improved care quality and patient outcomes.' },
      { text: 'News of the expansion drew patients from neighboring counties, and demand outgrew the new capacity.' },
      { text: 'The hospital also hired additional nurses during the same year to staff the new wing.' },
      { text: 'Emergency-room wait times had been falling for three years before the expansion began.' },
      { text: 'The hospital raised its parking fees last year, prompting complaints from visitors.' },
    ],
    correctIndex: 1,
    explanationQuick:
'More beds should shorten waits, yet waits grew. Choice (B) resolves it: publicity about the expansion attracted patients from surrounding counties, so demand outran the new supply. The distractors describe the wing, staffing, past trends, or parking — none of which explains demand outpacing capacity.',
    explanationWalkthrough:
'Two facts: capacity rose by 40 beds, but waits lengthened. Capacity alone does not set wait times — the balance of demand and capacity does. If demand grew faster than the added beds, waits rise despite the expansion. Choice (B) provides exactly that: news of the expansion pulled in patients from overcrowded neighboring counties, so the new beds were swamped by new demand. Choice (A) is the irrelevant-true trap: modern equipment does not explain the wait-time increase. Choice (C) deepens the mystery: more nurses should have shortened waits, making the rise stranger — the opposite trap. Choice (D) is background trivia about prior trends. Choice (E) is the irrelevant-true trap: parking fees do not drive emergency-room demand. Any genuine resolution must therefore operate on the demand side of the ledger — which is exactly what the influx of new patients from neighboring counties does.',
    choiceExplanations: [
'Modern equipment in the new wing does not explain why waits grew despite more beds. An unrelated facility detail is the irrelevant-true trap. Its truth is beside the point, since nothing in it connects to the inference being tested.',
'Correct. The expansion attracted patients from neighboring counties, so demand grew faster than the 40 new beds — waits rose because new demand swamped new supply.',
'Additional nurses should have reduced waits, making the increase more puzzling rather than less. This deepens the mystery: the opposite trap. Since it points in the opposite direction from the argument\'s conclusion, it cannot supply what the stem asks for.',
'The prior downward trend in waits is background that explains neither the expansion nor the reversal. This is the irrelevant-true trap. Its truth is beside the point, since nothing in it connects to the inference being tested.',
'Parking fees do not determine emergency-room demand or wait times. This is the irrelevant-true trap. Its truth is beside the point, since nothing in it connects to the inference being tested.',
    ],
    generalLesson:
'Capacity expansions can induce their own demand: when more supply coincides with longer waits, check whether the expansion itself attracted new users.',
    misconceptionTags: ['induced-demand', 'supply-demand-balance'],
    trapTypes: ['irrelevant-true', 'opposite', 'irrelevant-true', 'irrelevant-true'],
    prerequisites: ['lr-resolve-paradox', 'f-structure'],
    estimatedSeconds: 65,
    sourceType: 'original',
    hints: [
'Wait times depend on demand versus capacity, not capacity alone. What could make demand jump when beds were added?',
'Which choice brings new patients into the picture?',
'The correct choice: publicity drew patients from neighboring counties, swamping the new beds.',
    ],
    labels: { topic: 'hospital bed expansion' },
  },
  {
    id: 'lr-g-215',
    version: 1,
    sectionType: 'LR',
    questionType: 'lr-resolve-paradox',
    secondarySkills: ['f-structure', 'f-numbers', 'f-causation'],
    editorialDifficulty: 5,
    difficultyProfile: { structuralComplexity: 3, inferentialDistance: 5, scopeSubtlety: 4, distractorProximity: 4, causalComplexity: 3 },
    itemPurpose: 'mixed-discrimination',
    validationStatus: 'validated',
    stimulus:
'Last year brought record rainfall to the region. Yet the water level in the Halston Reservoir, the region\'s main water supply, fell to its lowest point in a decade.',
    stem: 'Which one of the following, if true, most helps to explain the apparent discrepancy described above?',
    choices: [
      { text: 'Regional water consumption rose to an all-time high last year, although the Halston Reservoir supplies less than five percent of the region\'s water.' },
      { text: 'The record rainfall figure was confirmed by three independent weather services.' },
      { text: 'Climate models predict more extreme rainfall for the region in coming decades.' },
      { text: 'Storms dropped rain outside the watershed; managers released large volumes to prevent downstream flooding.' },
      { text: 'The reservoir\'s dam underwent routine maintenance last spring.' },
    ],
    correctIndex: 3,
    explanationQuick:
'Record rain plus a falling reservoir is reconciled when the rain missed the watershed and the reservoir was deliberately drawn down: choice (D) explains both — storms hit coastal areas outside the catchment, while managers released stored water for flood control. The distractors cite consumption the reservoir barely serves, measurement verification, predictions, or maintenance without the dual mechanism.',
    explanationWalkthrough:
'This is a difficult item because two independent mechanisms must combine: the inflow side and the outflow side. Record regional rainfall should raise the reservoir — unless the rain did not fall in its watershed (inflow failed) and stored water was simultaneously released (outflow surged). Choice (D) supplies both: the storms struck coastal zones outside the reservoir\'s catchment, so the "record rainfall" never reached it, and managers preventively released large volumes to protect downstream towns from flooding. Both facts now coexist: regional rain records and a decade-low reservoir. Choice (A) is the half-right trap: record consumption elsewhere cannot draw down Halston when it supplies under five percent of regional water — the reservoir\'s own outflow side is untouched. Choice (B) is the irrelevant-true trap: verifying the rainfall record says nothing about which watershed received it or why the reservoir was drawn down. Choice (C) is the irrelevant-true trap: future predictions explain nothing about last year. Choice (E) is the unsupported trap: routine maintenance does not imply large releases.',
    choiceExplanations: [
'Record regional consumption cannot explain Halston\'s drop when the reservoir supplies less than five percent of the region\'s water — the consumption happened elsewhere. This addresses the wrong water body: the half-right trap.',
'That the rainfall record was verified changes nothing about where the rain fell or where the reservoir\'s water went. Confirming the measurement does not explain the paradox: the irrelevant-true trap.',
'Future climate predictions have no bearing on last year\'s reservoir level. This is the irrelevant-true trap. Its truth is beside the point, since nothing in it connects to the inference being tested.',
'Correct. The storms missed the reservoir\'s watershed (no inflow gain) while managers released stored water for flood control (large outflow) — the two mechanisms together reconcile record regional rain with a decade-low reservoir.',
'Routine maintenance does not imply that large volumes of water were released. Without the outflow mechanism, this is the unsupported trap. With the key claim left unsupported by any evidence, it cannot do the work the correct choice does.',
    ],
    generalLesson:
'Hard paradoxes often need two mechanisms — one for each side of the ledger. Check inflows and outflows (or supply and demand) separately before settling for a one-sided story.',
    misconceptionTags: ['two-mechanism', 'watershed-scope'],
    trapTypes: ['half-right', 'irrelevant-true', 'irrelevant-true', 'unsupported'],
    prerequisites: ['lr-resolve-paradox', 'f-structure', 'f-numbers'],
    estimatedSeconds: 105,
    sourceType: 'original',
    hints: [
'A reservoir\'s level depends on water in versus water out. Which choice addresses both sides?',
'Record regional rain means little if it fell outside the watershed — and what might managers have been releasing water for?',
'The correct choice pairs missed-watershed storms with preventive flood-control releases.',
    ],
    labels: { topic: 'reservoir water level' },
    reviewHistory: [
      { date: '2026-09-11', reviewer: 'hostile-sample-2026-09-11', verdict: 'validate',
        notes: 'Independent 40-item hostile audit: KEEP (good diff-5); 0 two-defensible findings; leakage pass 2 applied.' },
    ],
  },
  {
    id: 'lr-g-216',
    version: 1,
    sectionType: 'LR',
    questionType: 'lr-resolve-paradox',
    secondarySkills: ['f-structure'],
    editorialDifficulty: 3,
    difficultyProfile: { structuralComplexity: 2, inferentialDistance: 3, distractorProximity: 3 },
    itemPurpose: 'independent-blocked',
    validationStatus: 'validated',
    reviewHistory: [
      { date: '2026-09-11', reviewer: 'full-lr-classification-2026-09-11', verdict: 'validate',
        notes: 'Full-LR classification: KEEP. Shelf-displacement cannibalization mechanism; d3 honest.' },
    ],
    stimulus:
'A beloved independent bookstore added a café to attract more foot traffic. In the year that followed, the store\'s book sales fell by 22 percent.',
    stem: 'Which one of the following, if true, most helps to explain the apparent discrepancy described above?',
    choices: [
      { text: 'To make room for the café, the store removed a third of its bookshelves, cutting displayed titles' },
      { text: 'The café itself was profitable in its first year, drawing steady crowds on weekends.' },
      { text: 'Book sales fell at independent bookstores nationwide during the same year, reflecting broader trends.' },
      { text: 'The store extended its opening hours when the café was added, staying open two hours later.' },
      { text: 'Many customers now buy coffee and browse without purchasing books, treating the store as a café.' },
    ],
    correctIndex: 0,
    explanationQuick:
'A café should bring more browsers who buy books, yet book sales fell. Choice (A) resolves it: the café displaced a third of the shelves, so the smaller selection sold fewer books — the traffic gain could not offset the shrunken inventory. The distractors cite café profits, national trends, hours, or browsing without the displacement mechanism.',
    explanationWalkthrough:
'Two facts: a café was added to boost traffic, but book sales dropped 22%. For both to hold, the café must have harmed book-selling capacity more than the extra traffic helped. Choice (A) supplies the mechanism: a third of the bookshelves were removed, so the range of titles — the store\'s reason for existing — shrank sharply, and fewer titles meant fewer sales. The café succeeded at drawing people but cannibalized the book business physically. Choice (B) is the half-right trap: café profits explain the café, not the book-sales decline. Choice (C) is also half-right: a national downturn might contribute, but it does not explain this store\'s specific divergence between the traffic strategy and the sales result. Choice (D) deepens the mystery: longer hours should have helped sales. Choice (E) is the tempting near-miss — browsers who buy only coffee — but without the shelf displacement it does not explain a 22% sales collapse; it describes a symptom, not the mechanism.',
    choiceExplanations: [
'Correct. Removing a third of the shelves shrank the title selection that drives book sales — the café boosted foot traffic but physically displaced the book business, reconciling both facts.',
'Café profitability explains the café\'s success, not the 22% drop in book sales. Addressing only one side is the half-right trap. It captures part of the structure while missing the load-bearing element, which is exactly why it fails.',
'A national downturn might contribute, but it does not explain why this store\'s traffic-boosting strategy coincided with a sales collapse. This is the half-right trap.',
'Longer opening hours should have supported sales, making the decline stranger. This deepens the mystery: the opposite trap. Since it points in the opposite direction from the argument\'s conclusion, it cannot supply what the stem asks for.',
'Coffee-only browsers describe a symptom, but without the shelf displacement it does not explain why sales fell 22% rather than merely shifting. This is the half-right trap.',
    ],
    generalLesson:
'An addition that displaces the core product can hurt overall: when a traffic strategy coincides with falling sales, check what the new attraction physically replaced.',
    misconceptionTags: ['cannibalization', 'displacement'],
    trapTypes: ['half-right', 'half-right', 'opposite', 'half-right'],
    prerequisites: ['lr-resolve-paradox', 'f-structure'],
    estimatedSeconds: 80,
    sourceType: 'original',
    hints: [
'The café was supposed to bring browsers who buy books. What if the café hurt the book side of the store directly?',
'Which choice says the café physically replaced bookselling capacity?',
'The correct choice: a third of the shelves were removed for the café, shrinking the selection that drives sales.',
    ],
    labels: { topic: 'bookstore café' },
  },
  {
    id: 'lr-g-217',
    version: 1,
    sectionType: 'LR',
    questionType: 'lr-resolve-paradox',
    secondarySkills: ['f-structure', 'f-numbers'],
    editorialDifficulty: 2,
    difficultyProfile: { structuralComplexity: 2, inferentialDistance: 3, distractorProximity: 3, abstraction: 2, linguisticComplexity: 1 },
    itemPurpose: 'independent-blocked',
    validationStatus: 'validated',
    stimulus:
'An airline added daily flights on its most popular route. Despite the increase in available seats, the percentage of seats filled on the route rose.',
    stem: 'Which one of the following, if true, most helps to explain the apparent discrepancy described above?',
    choices: [
      { text: 'The airline also reduced the number of flight attendants per flight to cut operating costs.' },
      { text: 'A competing airline canceled all its flights on the same route, and its former passengers shifted to the remaining carrier.' },
      { text: 'The new flights were scheduled at off-peak times when demand is usually low, limiting their appeal to business travelers especially.' },
      { text: 'Ticket prices on the route remained unchanged throughout the entire period.' },
      { text: 'The airline\'s on-time performance was unchanged during the same period, remaining above average.' },
    ],
    correctIndex: 1,
    explanationQuick:
'More seats should dilute the load factor, yet it rose. Choice (B) resolves it: a competitor exited the route, so its passengers flooded onto the remaining flights — demand grew faster than the new seats. The distractors address staffing, scheduling, prices, or punctuality without the demand surge.',
    explanationWalkthrough:
'Load factor is passengers divided by seats. Seats rose, yet the ratio rose too — so passenger numbers must have grown even faster. An external demand shock explains it. Choice (B): a rival canceled all its flights on the route, dumping its former passengers onto this airline\'s expanded schedule. Both facts hold: more seats, and an even larger influx of passengers. Choice (A) is the irrelevant-true trap: staffing does not affect the load factor. Choice (C) deepens the mystery: off-peak flights should have lowered the fill rate. Choice (D) is the half-right trap: unchanged prices might sustain demand, but they do not explain a surge in passengers outpacing new seats. Choice (E) is the irrelevant-true trap: unchanged punctuality cannot explain passengers outpacing new seats.',
    choiceExplanations: [
'Flight-attendant staffing has no bearing on the percentage of seats filled. An unrelated operational detail is the irrelevant-true trap. Its truth is beside the point, since nothing in it connects to the inference being tested.',
'Correct. The competitor\'s exit shifted its entire passenger base onto the remaining flights, so passenger growth outpaced the new seats — reconciling more capacity with a higher load factor.',
'Off-peak scheduling should dilute the fill rate, making the rise stranger. This deepens the mystery: the opposite trap. Since it points in the opposite direction from the argument\'s conclusion, it cannot supply what the stem asks for.',
'Unchanged prices might sustain existing demand but cannot explain a passenger surge large enough to outrun added seats. This is the half-right trap. It captures part of the structure while missing the load-bearing element, which is exactly why it fails.',
'Unchanged on-time performance explains nothing about why seat occupancy rose faster than capacity — a static fact cannot drive the demand surge. This is the irrelevant-true trap.',
    ],
    generalLesson:
'Ratios follow the faster-moving side: when capacity and fill rates rise together, look for an external demand shock — like a competitor\'s exit — outpacing the new supply.',
    misconceptionTags: ['ratio-arithmetic', 'demand-shock'],
    trapTypes: ['irrelevant-true', 'opposite', 'half-right', 'irrelevant-true'],
    prerequisites: ['lr-resolve-paradox', 'f-structure', 'f-numbers'],
    estimatedSeconds: 65,
    sourceType: 'original',
    hints: [
'Load factor is passengers divided by seats. If seats rose and the ratio still rose, what must have happened to passengers?',
'Which choice delivers a surge of new passengers from outside the airline?',
'The correct choice: a competitor left the route, and its passengers moved over.',
    ],
    labels: { topic: 'airline load factor' },
    reviewHistory: [
      { date: '2026-09-11', reviewer: 'hostile-sample-2026-09-11', verdict: 'validate',
        notes: 'Independent 40-item hostile audit: KEEP; 0 two-defensible findings; leakage pass 2 applied.' },
    ],
  },
  {
    id: 'lr-g-218',
    version: 1,
    sectionType: 'LR',
    questionType: 'lr-resolve-paradox',
    secondarySkills: ['f-structure', 'f-causation'],
    editorialDifficulty: 4,
    difficultyProfile: { structuralComplexity: 3, inferentialDistance: 4, distractorProximity: 3 },
    itemPurpose: 'mixed-discrimination',
    validationStatus: 'validated',
    reviewHistory: [
      { date: '2026-09-11', reviewer: 'full-lr-classification-2026-09-11', verdict: 'validate',
        notes: 'Full-LR classification: KEEP. Filled-vs-total positions distinction via chronic vacancies; d4 honest.' },
    ],
    stimulus:
'When the state raised its minimum wage, economists predicted employment in low-wage sectors would fall. Instead, the number of filled low-wage positions rose over the following year.',
    stem: 'Which one of the following, if true, most helps to explain the apparent discrepancy described above?',
    choices: [
      { text: 'Many businesses raised their prices to cover the higher labor costs, passing the increase on to consumers throughout the region.' },
      { text: 'The wage increase applied only to workers over the age of 21, leaving teenage employment patterns largely unaffected.' },
      { text: 'Neighboring states that did not raise the minimum wage saw employment hold steady in low-wage sectors throughout the same period.' },
      { text: 'Several large employers announced layoffs in the same year, citing automation rather than wage levels in their public statements.' },
      { text: 'Chronic unfilled vacancies plagued low-wage sectors, and the higher wage drew workers from neighboring counties, filling empty posts' },
    ],
    correctIndex: 4,
    explanationQuick:
'Higher wages should price some jobs out, yet filled positions rose. Choice (E) resolves it through vacancies: the sectors had chronic unfilled openings, and the raise attracted workers who filled them — the count of filled positions grew even if total job slots did not. The distractors cite prices, age limits, neighbors, or layoffs without the vacancy mechanism.',
    explanationWalkthrough:
'The subtlety is "filled positions" versus "total positions." Economists predicted fewer jobs would exist; the statistic counts jobs actually filled. If many slots stood vacant, a wage hike can increase filled positions by drawing workers into empty slots — without creating a single new job. Choice (E) builds exactly this: chronic vacancies plus an in-migration of workers from neighboring counties at the higher wage, so filled positions rose. Both facts hold: the wage rose, and more positions were filled, with no contradiction. Choice (A) is the half-right trap: higher prices might offset labor costs but do not explain more filled positions. Choice (B) is the irrelevant-true trap: an age restriction does not explain the aggregate rise. Choice (C) is the half-right trap: steady neighbors provide no mechanism for this state\'s increase. Choice (D) deepens the mystery: layoffs should have reduced filled positions.',
    choiceExplanations: [
'Higher prices might protect margins, but they do not explain why more low-wage positions got filled. This addresses costs, not the employment count: the half-right trap.',
'An age restriction on the wage law does not explain the overall rise in filled positions. An unrelated policy detail is the irrelevant-true trap. Its truth is beside the point, since nothing in it connects to the inference being tested.',
'Steady employment in neighboring states provides no mechanism for this state\'s increase. This is the half-right trap. It captures part of the structure while missing the load-bearing element, which is exactly why it fails.',
'Large-employer layoffs should have reduced filled positions, making the rise stranger. This deepens the mystery: the opposite trap. Since it points in the opposite direction from the argument\'s conclusion, it cannot supply what the stem asks for.',
'Correct. Chronic vacancies meant jobs existed but stood empty; the higher wage drew workers from neighboring counties into those slots, so filled positions rose — reconciling the wage hike with higher employment counts.',
    ],
    generalLesson:
'Distinguish stocks from flows and filled from vacant: when a price rise coincides with higher counts, check whether the count measures filled slots against a backlog of vacancies.',
    misconceptionTags: ['filled-vs-vacant', 'vacancy-backlog'],
    trapTypes: ['half-right', 'irrelevant-true', 'half-right', 'opposite'],
    prerequisites: ['lr-resolve-paradox', 'f-structure', 'f-causation'],
    estimatedSeconds: 95,
    sourceType: 'original',
    hints: [
'The statistic counts filled positions. Could positions have existed but stood empty before the raise?',
'Which choice describes a backlog of vacancies waiting for workers?',
'The correct choice: chronic vacancies plus higher wages drew in county workers, filling long-empty slots.',
    ],
    labels: { topic: 'minimum wage employment' },
  },
  {
    id: 'lr-g-219',
    version: 1,
    sectionType: 'LR',
    questionType: 'lr-resolve-paradox',
    secondarySkills: ['f-structure'],
    editorialDifficulty: 1,
    difficultyProfile: { structuralComplexity: 1, inferentialDistance: 2, distractorProximity: 2, linguisticComplexity: 1 },
    itemPurpose: 'skill-acquisition',
    validationStatus: 'validated',
    stimulus:
'The town repaved all of its main roads last summer. In the months that followed, local car repair shops reported a surge in suspension and alignment work.',
    stem: 'Which one of the following, if true, most helps to explain the apparent discrepancy described above?',
    choices: [
      { text: 'Smooth new pavement encourages faster driving, which wears out tires more quickly over time.' },
      { text: 'During repaving, detours sent traffic over rough gravel roads, damaging suspensions and alignment' },
      { text: 'The repaving project finished several weeks ahead of schedule.' },
      { text: 'Car repair shops raised their prices after the repaving was completed last summer.' },
      { text: 'The town also repaved its bicycle paths during the same summer construction season.' },
    ],
    correctIndex: 1,
    explanationQuick:
'Smooth new roads should mean fewer repairs, yet shops got busier. Choice (B) resolves it: the damage came not from the new pavement but from the construction period — weeks of detours over rough gravel battered suspensions. The distractors blame speed, cite schedules, or raise irrelevant details.',
    explanationWalkthrough:
'Two facts: roads were repaved (smooth), but suspension work surged. The resolution must locate the damage somewhere other than the finished roads. Choice (B) does: during construction, detours forced cars onto rough gravel for weeks, and that is what damaged suspensions — the surge reflects the construction period, not the new pavement. Choice (A) is the half-right trap: faster driving on smooth roads might wear tires, but the surge was in suspension and alignment work specifically, and the mechanism is speculative. Choice (C) is the irrelevant-true trap: finishing early explains nothing about repairs. Choice (D) is also irrelevant: shop pricing does not explain the volume of suspension work. Choice (E) is the irrelevant-true trap: bicycle paths do not affect car suspensions.',
    choiceExplanations: [
'Faster driving might wear tires, but the surge was specifically in suspension and alignment work — and this does not explain damage tied to the repaving period. This is the half-right trap.',
'Correct. The damage came from weeks of detour traffic over rough gravel during construction — not from the smooth new pavement — reconciling the repaving with the repair surge.',
'Finishing ahead of schedule is project trivia that explains nothing about suspension damage. This is the irrelevant-true trap. Its truth is beside the point, since nothing in it connects to the inference being tested.',
'Shop pricing affects revenue, not the volume of suspension work reported. This is the irrelevant-true trap. Its truth is beside the point, since nothing in it connects to the inference being tested.',
'Bicycle paths have no bearing on car suspensions and alignments. This is the irrelevant-true trap. Its truth is beside the point, since nothing in it connects to the inference being tested.',
    ],
    generalLesson:
'The transition can cause what the result prevents: when an improvement coincides with harm, check whether the disruption of getting there did the damage.',
    misconceptionTags: ['transition-effect', 'construction-period'],
    trapTypes: ['half-right', 'irrelevant-true', 'irrelevant-true', 'irrelevant-true'],
    prerequisites: ['lr-resolve-paradox', 'f-structure'],
    estimatedSeconds: 50,
    sourceType: 'original',
    hints: [
'The finished roads are smooth — so where did the damage come from? Think about the repaving period itself.',
'Which choice describes what drivers endured while the work was underway?',
'The correct choice: weeks of detours over rough gravel battered suspensions during construction.',
    ],
    labels: { topic: 'road repaving repairs' },
    reviewHistory: [
      { date: '2026-09-11', reviewer: 'hostile-sample-2026-09-11', verdict: 'validate',
        notes: 'Independent 40-item hostile audit: KEEP; 0 two-defensible findings; leakage pass 2 applied.' },
    ],
  },
  {
    id: 'lr-g-220',
    version: 2,
    revisedAt: '2026-09-11',
    sectionType: 'LR',
    questionType: 'lr-resolve-paradox',
    secondarySkills: ['f-structure', 'f-numbers', 'f-samples'],
    editorialDifficulty: 5,
    difficultyProfile: { structuralComplexity: 4, inferentialDistance: 4, distractorProximity: 4 },
    itemPurpose: 'mixed-discrimination',
    validationStatus: 'validated',
    reviewHistory: [
      { date: '2026-09-11', reviewer: 'full-lr-classification-2026-09-11', verdict: 'validate',
        notes: 'Full-LR classification: REVISE-fixed v2. Hostile review found two independently defensible distractors: (A) budget-cut mechanism and (E) harder-test mechanism both coherently resolved the paradox. Neutralized: (A) now grant-funded with no cuts (qualifier catch), (E) now paired with rising statewide averages (opposite trap). (D) Simpson\u2019s-paradox composition mechanism is now uniquely correct; d5 honest.' },
    ],
    stimulus:
'A school district launched an intensive tutoring program for struggling students. At the end of the year, the district\'s average test score had fallen — even though independent evaluators confirmed the tutoring genuinely helped every student who received it.',
    stem: 'Which one of the following, if true, most helps to explain the apparent discrepancy described above?',
    choices: [
      { text: 'The tutoring program was expensive, but it was paid for entirely from a dedicated state grant, and no other academic programs were cut that year.' },
      { text: 'High-performing students took the test at exactly the same rate as in previous years, so the decline in the average did not come from them.' },
      { text: 'Teachers reported that tutored students seemed more confident and engaged in class afterward.' },
      { text: 'The program drew low-performing students new to the test; their newly counted scores lowered the mean as tutored students improved' },
      { text: 'The test was redesigned that year to include more difficult questions in every subject \u2014 yet statewide average scores rose that year.' },
    ],
    correctIndex: 3,
    explanationQuick:
'Effective tutoring plus a falling average is reconciled by a changed test-taking pool: choice (D) explains that the program brought previously untested low performers into the testing pool, so the average fell even as every tutored student improved. The distractors note steady high-performer turnout and confidence, or raise budget and redesign hypotheses that the choices themselves close off \u2014 a grant qualifier rules out program cuts, and rising statewide averages rule out the harder test.',
    explanationWalkthrough:
'This is the hardest item because it requires holding three facts at once: the tutoring helped every recipient, yet the average fell. Both can hold only if the composition of the averaged group changed: adding low scores to the pool drags the average down even when each added student improved relative to their own baseline. Choice (D) constructs exactly this Simpson\'s-paradox mechanism: the program drew in the lowest performers, many previously untested, so their scores entered the average for the first time — each improved by tutoring, but from such a low base that the district average fell. Choice (A) is the irrelevant-true trap with a qualifier catch: the program was expensive, but a dedicated grant covered the cost and no other programs were cut — the budget-cut mechanism a hasty reader infers is explicitly ruled out by the choice itself. Topical and true, yet with its mechanism removed it explains nothing. Choice (B) is the irrelevant-true trap: steady participation by high performers eliminates one alternative, but explains nothing about the falling average. Choice (C) is the irrelevant-true trap: confidence is not the test average. Choice (E) is the opposite trap: a redesigned, harder test should depress scores everywhere, yet statewide averages rose that year — so the redesign cannot explain this district\'s falling average, and the mystery deepens instead of resolving.',
    choiceExplanations: [
'The program was expensive, but a dedicated grant covered the cost and no other programs were cut — the budget-cut story a hasty reader infers is explicitly ruled out by the choice itself. Topical and true, but with its mechanism removed it explains nothing: the irrelevant-true trap.',
'Steady test-taking by high performers rules out one alternative story, but it explains nothing about why the average fell while every tutored student improved. Eliminating an alternative is not a resolution: the irrelevant-true trap.',
'Student confidence is not the district\'s average test score. An unrelated feel-good detail is the irrelevant-true trap. Its truth is beside the point, since nothing in it connects to the inference being tested.',
'Correct. Previously untested low performers entered the testing pool through the program; their newly counted scores pulled the average down even though tutoring improved each of them — reconciling genuine gains with a falling average.',
'A redesigned, harder test should depress scores everywhere — yet statewide averages rose that year, so the redesign cannot explain this district\'s falling average. Instead of resolving the puzzle it deepens it: the opposite trap.',
    ],
    generalLesson:
'Averages follow pool composition: when an intervention helps everyone it touches yet the average falls, ask who newly entered the pool — and from how low a base.',
    misconceptionTags: ['simpsons-paradox', 'pool-composition'],
    trapTypes: ['irrelevant-true', 'irrelevant-true', 'irrelevant-true', 'opposite'],
    prerequisites: ['lr-resolve-paradox', 'f-structure', 'f-numbers'],
    estimatedSeconds: 110,
    sourceType: 'original',
    hints: [
'Every tutored student improved, yet the average fell. What if the group being averaged is not the same group as last year?',
'Who might the program have brought into the testing pool for the first time?',
'The correct choice: previously untested low performers entered the pool — each improved, but their low scores dragged the average down.',
    ],
    labels: { topic: 'tutoring program paradox' },
  },
];